# Generated by Django 6.0 on 2025-12-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('css_class', models.CharField(max_length=50)),
                ('button_text', models.CharField(max_length=100)),
                ('button_link', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
