# Generated by Django 6.0 on 2025-12-09 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название концепции')),
                ('icon', models.CharField(max_length=10, verbose_name='Иконка')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет (HEX или название)')),
                ('description', models.CharField(max_length=100, verbose_name='Описание концепции')),
            ],
            options={
                'verbose_name': 'Концепция',
                'verbose_name_plural': 'Концепции',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название предмета')),
                ('subtitle', models.CharField(max_length=150, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('button_text', models.CharField(default='Перейти к курсу', max_length=100, verbose_name='Текст кнопки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступность')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.concept', verbose_name='Концепция')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
