# Generated by Django 6.0 on 2025-12-09 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='color',
            field=models.CharField(default='фиолетовый', help_text='Пример: "фиолетовый", "зелёный", "синий"', max_length=20, verbose_name='Цвет (название)'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='description',
            field=models.CharField(help_text='Пример: "право и справедливость", "технологии и цифра"', max_length=100, verbose_name='Описание концепции'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='icon',
            field=models.CharField(help_text='Пример: "⚖️", "💻", "📈"', max_length=10, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='name',
            field=models.CharField(help_text='Пример: "Юриспруденция", "Экономисты", "Программисты"', max_length=50, verbose_name='Название профессии'),
        ),
        migrations.AlterField(
            model_name='course',
            name='button_text',
            field=models.CharField(default='Перейти к курсу', help_text='Текст кнопки для перехода к курсу', max_length=100, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='course',
            name='concept',
            field=models.ForeignKey(help_text='Выберите концепцию, к которой относится курс', on_delete=django.db.models.deletion.CASCADE, to='core.concept', verbose_name='Концепция'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='Пример: "Подробный курс по гражданскому праву для начинающих."', verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Если курс неактивен, кнопка будет недоступна', verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subtitle',
            field=models.CharField(help_text='Пример: "Основы права", "Введение в экономику", "Основы программирования на Python"', max_length=150, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='Пример: "Гражданское право", "Экономика", "Python для начинающих"', max_length=100, verbose_name='Название предмета'),
        ),
    ]
