# Generated by Django 6.0 on 2025-12-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='button_link',
        ),
        migrations.AlterField(
            model_name='course',
            name='button_text',
            field=models.CharField(default='Перейти к курсу', max_length=100, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='course',
            name='color',
            field=models.CharField(max_length=20, verbose_name='Цвет концепции'),
        ),
        migrations.AlterField(
            model_name='course',
            name='css_class',
            field=models.CharField(max_length=50, verbose_name='CSS-класс для карточки'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='icon',
            field=models.CharField(max_length=10, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Курс доступен'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subtitle',
            field=models.CharField(max_length=150, verbose_name='Краткое описание (pill)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название предмета'),
        ),
    ]
