# Generated by Django 6.0 on 2025-12-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_course_options_remove_course_button_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='css_class',
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Описание курса'),
        ),
    ]
