# Generated by Django 6.0 on 2025-12-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_concept_color_alter_concept_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='Пример: "Законы, права человека, ответственность. Вопросы по Конституции и базовым кодексам."', verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subtitle',
            field=models.CharField(help_text='Пример: "Основы права", "Введение в экономику"', max_length=150, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='Пример: "Юриспруденция", "Экономика""', max_length=100, verbose_name='Название предмета'),
        ),
    ]
